### ISSUE TITLE
Automatically load exrc when changing directory with cd

### ISSUE THREAD

**Issue by metziger23** [jedrzejboczar/exrc.nvim#2]
Hello, first of all I would like to thank you for this plugin. I faced the issue when I had to source .nvim.lua files manually with overseer tasks after changing current working directory and this plugin gives me an opportunity to do this more conveniently. 
However there's one thing that I don't understand about this plugin and it's related to "Automatically load exrc when changing directory with cd". 
Steps to reproduce:
1. Create two directories on the same level.
` mkdir dir1 dir2`
2. Create .nvim.lua with overseer task in dir1 and .nvim.lua  with overseer task in dir2.
```
local ctx = require('exrc').init()
require("overseer").register_template({
	name = "hello dir1",
	params = {},
	condition = {
		dir = ctx.exrc_dir,
	},
	builder = function()
		return {
			cmd = "echo hello_dir1",
      cwd = ctx.exrc_dir,
			components = { "default" },
		}
	end,
})
```
.nvim.lua in dir2 has the same task but with dir2 in name and cmd

3. Open neovim in dir1.
`cd dir1 && nvim`
.nvim.lua in dir1 was sourced automatically.

4. cd into dir2.
`:cd ../dir2`

Actual results:
.nvim.lua in dir2 wasn't sourced automaticaly. I can load it using `:ExrcLoad`.

Expected results:
I would like .nvim.lua in dir2 to be loaded (sourced) automatically.

I used the default config for the exrc.nvim plugin
```
return {
  "jedrzejboczar/exrc.nvim",
  config = true
}
```
I set vim.opt.exrc to false
`vim.opt.exrc = false`

my nvim version:

NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202

But I downloaded and tried nightly and the behavior was the same

NVIM v0.11.0-dev-250+g61aabe073
Build type: RelWithDebInfo
LuaJIT 2.1.1716656478

**Comment by metziger23** [comment]
As a workaround I forked this repo and changed the code in function `on_dir_changed`
I forced this function to do the same thing that on `on_vim_enter` does.
https://github.com/jedrzejboczar/exrc.nvim/commit/f0d1256d547e05e10e145ccf24cad62012794d9a

Now after I change a directory with `cd` the .nvim.lua gets loaded automatically.

**Comment by metziger23** [comment]
Could you give an opportunity to automatically load .nvim.lua as it is in my forked repo? Maybe add an option to give a user of this plugin an opportunity to achieve this behavior?

**Comment by jedrzejboczar** [comment]
I tried to reproduce this, but I get what this plugin always did, i.e. after you `:cd ../dir2` you should get a `vim.ui.select` prompt to select the files to load. Are you using something like [dressing.nvim](https://github.com/stevearc/dressing.nvim) or the built-in `vim.ui.select`?

The reason for this `vim.ui.select` behaviour is because I sometimes don't want to load exrc files on `cd` so it uses UI requiring user to confirm loading. I could add a config option to avoid this and always load unconditionally. 

Could you provide some logs? You would have to set `min_log_level = vim.log.levels.TRACE` in the setup function. Here is how it looks like for me:
```
2024-06-17T09:17:41 ✎ TRACE exrc.on_vim_enter(/tmp/exrc-test/dir1): found
2024-06-17T09:17:41 ✎ TRACE exrc.load(/tmp/exrc-test/dir1/.nvim.lua)
2024-06-17T09:17:41 ✎ TRACE exrc.db_remove(/tmp/exrc-test/dir1/.nvim.lua)
2024-06-17T09:17:41  DEBUG Loading exrc "/tmp/exrc-test/dir1/.nvim.lua"
2024-06-17T09:17:41 ✎ TRACE exrc.mark_loaded(/tmp/exrc-test/dir1/.nvim.lua)
2024-06-17T09:17:44 Messages  INFO /tmp/exrc-test/dir2
2024-06-17T09:17:44 Notify ✎ TRACE exrc.on_dir_changed(/tmp/exrc-test/dir2/)
2024-06-17T09:17:44 Notify ✎ TRACE exrc.ui_load(#1, nil): aleady_pending=0
2024-06-17T09:17:45 Notify ✎ TRACE exrc.load_pending(#1)
2024-06-17T09:17:45 Notify ✎ TRACE exrc.load(/tmp/exrc-test/dir2/.nvim.lua)
2024-06-17T09:17:45 Notify ✎ TRACE exrc.db_remove(/tmp/exrc-test/dir2/.nvim.lua)
2024-06-17T09:17:45 Notify  DEBUG Loading exrc "/tmp/exrc-test/dir2/.nvim.lua"
2024-06-17T09:17:45 Notify ✎ TRACE exrc.mark_loaded(/tmp/exrc-test/dir2/.nvim.lua)
2024-06-17T09:17:45 Notify  INFO Loaded 1/1 files
```

**Comment by jedrzejboczar** [comment]
I noticed there was a bug when `vim.ui.select` has not been replaced and you select the file to load. It's now fixed in https://github.com/jedrzejboczar/exrc.nvim/commit/48fd72df148c41f50139a3ebee20cce2342c7a00.

**Comment by metziger23** [comment]
Thank you for your response. 
I put `min_log_level = vim.log.levels.TRACE` in the setup function.
When I `cd` from dir1 to di2 neovim gives me the following message:
```
exrc.on_dir_changed(/Volumes/k/Misc/overseer-test-dir/dir2/)                                                                                                                                                                            
exrc.ui_load(#1, nil): aleady_pending=0                                                                                                                                                                                                 
/Volumes/k/Misc/overseer-test-dir/dir2                                                                                                                                                                                                           
```                                                                                                                                                                                          

Then after a while I get TelescopePrompt that asks me to select a `.tasks.lua `
(I set this name in      ` exrc_name = '.tasks.lua', -- Name of exrc files to use`, previously I experimented with `.nvim.lua` files, the behavior was the same)
but this TelescopePrompt doesn't appear instantly, it appears only after some delay (I don't know why)
I also tried to disable/enable [dressing.nvim](https://github.com/stevearc/dressing.nvim) but it changed nothing
My OS is Apple M2 macOS Sonoma Version 14.4.1 but I'm not sure if this really matters
<img width="936" alt="image" src="https://github.com/jedrzejboczar/exrc.nvim/assets/87540557/6ac5949b-39a3-4a4b-be5a-ff62ec401239">

**Comment by metziger23** [comment]
Anyway, the option to load `.nvim.lua` unconditionally (without a prompt that asks me to select a file to source) would be enough since in my case I very rarely don't want to load a task file that's contained in a directory where I did `cd` and even if I load the file unintentionally I can unload it using ExrcUnload

**Comment by jedrzejboczar** [comment]
Ok, I'll make this configurable, the delay might be unwanted depending on how one uses this plugin.

Regarding the delay, it waits for `CursorHold` to fire, so it will take `'updatetime'` milliseconds. I use `set updatetime=300` so it is fast, but the default is 4000 which may be very slow (I feel like the default is too long in general). The logic behind this behaviour is the following:
* I often find myself loading sessions
* my sessions usually have a global cwd and some other different tab-local cwds
* after loading session this would automatically load all the `.nvim.lua` files, which I don't always want
* so this plugin waits for CursorHold, queueing up all the loads, then it uses `vim.ui.select` to load the files that I want
Also, it won't open as long as you are in a floating window, to avoid it breaking Telescope searches, etc.

**Comment by jedrzejboczar** [comment]
It should now work with https://github.com/jedrzejboczar/exrc.nvim/commit/4346164895f432f361e453d837b612e6c7cbe3e6.

**Comment by metziger23** [comment]
> Ok, I'll make this configurable, the delay might be unwanted depending on how one uses this plugin.
> 
> Regarding the delay, it waits for `CursorHold` to fire, so it will take `'updatetime'` milliseconds. I use `set updatetime=300` so it is fast, but the default is 4000 which may be very slow (I feel like the default is too long in general). The logic behind this behaviour is the following:
> 
>     * I often find myself loading sessions
> 
>     * my sessions usually have a global cwd and some other different tab-local cwds
> 
>     * after loading session this would automatically load all the `.nvim.lua` files, which I don't always want
> 
>     * so this plugin waits for CursorHold, queueing up all the loads, then it uses `vim.ui.select` to load the files that I want
>       Also, it won't open as long as you are in a floating window, to avoid it breaking Telescope searches, etc.

Yes, I think the delay was related to `'updatetime'`.  Thank you for your effort and adding the new option!
Since my problem seems solved I close the issue
